version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'node:latest'

    working_directory: ~/QAlenium-Python

    steps:
      - checkout
      - sonarcloud/scan


workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master